import setuptools

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    name="TOF-SIMS", # Replace with your own username
    version="0.0.1",
    author="Daniel Oldfield, Remi Branco",
    author_email="daniel.thomas.oldfield@gmail.com, remi.branco@hotmail.fr",
    description="Open and process 3D datasets generated by TOF-SIMS (Tescan) microscope",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Remi-Branco/TOF-SIMS-package",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GPL-3.0 License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
