import setuptools

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    name="TOF-SIMS", # Replace with your own username
    version="0.0.1",
    author="Daniel Oldfield, Remi Branco",
    author_email="danielo@ansto.gov.au, remi.branco@hotmail.fr",
    description="Open and process datasets generated by TOF-SIMS (Tecan) microscope",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/pypa/sampleproject",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
